### Get All entries in the database(persons array)
GET http://localhost:3001/api/persons HTTP/1.1

### Get total number of entries in database(persons array)

GET http://localhost:3001/info HTTP/1.1

### Get the full record of one entry

GET http://localhost:3001/api/persons/1 HTTP/1.1


### Delete an Entry from the phonebook

DELETE http://localhost:3001/api/persons/5 HTTP/1.1


### Enter a new entry to the phonebook

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Dummy Entry",
    "number": "040-2789-4511"
}

### checking of short length validation of a new entry to the phonebook

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Te",
    "number": "040-2789-4511"
}

### Unknown entrypoint
GET http://localhost:3001/unknown HTTP/1.1


